### ISSUE TITLE
Checklist mode is not implemented in Metanorma

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/hk-ogcio-infosec-docs#13]
I think list items in checklist mode isn't implemented in Metanorma.

For example, in the following markup:
````
== Checklist sample

- [ ] Information System Manager
- [ ] Information Coordinator
- [ ] Incident Response Manager
- [ ] ISIRT Commander
- [ ] GIRO Standing Office
````
The respective outputs (ascciidoctor vs metanorma) are:

_Asciidoctor:_
![asciidoctor-output](https://user-images.githubusercontent.com/33627611/73547469-681db200-4415-11ea-9a57-23cd1082cc2f.JPG)

_Metanorma (DOC):_ 
![metanorma-output](https://user-images.githubusercontent.com/33627611/73547480-6bb13900-4415-11ea-891d-188488a7ca42.JPG)

Sample file: 
[checklist-bug.zip](https://github.com/riboseinc/hk-ogcio-infosec-docs/files/4139871/checklist-bug.zip)

**Comment by ronaldtse** [comment]
@manuel489 thanks for filing this! Can you re-post this issue to metanorma-standoc too?

**Comment by manuelfuenmayor** [comment]
Sure @ronaldtse , here it is: https://github.com/metanorma/metanorma-standoc/issues/199
(As you can see, I just put a link to this issue. Please let me know if you want me to transfer all the content.)

**Comment by manuelfuenmayor** [comment]
Issue transferred to: https://github.com/metanorma/metanorma-standoc/issues/199
